use v6.c;

use NativeCall;

use GLib::Raw::Definitions;

unit package GSK::Raw::Enunms:ver<4>;

constant GskBlendMode is export := guint32;
our enum GskBlendModeEnum is export <
  GSK_BLEND_MODE_DEFAULT
  GSK_BLEND_MODE_MULTIPLY
  GSK_BLEND_MODE_SCREEN
  GSK_BLEND_MODE_OVERLAY
  GSK_BLEND_MODE_DARKEN
  GSK_BLEND_MODE_LIGHTEN
  GSK_BLEND_MODE_COLOR_DODGE
  GSK_BLEND_MODE_COLOR_BURN
  GSK_BLEND_MODE_HARD_LIGHT
  GSK_BLEND_MODE_SOFT_LIGHT
  GSK_BLEND_MODE_DIFFERENCE
  GSK_BLEND_MODE_EXCLUSION
  GSK_BLEND_MODE_COLOR
  GSK_BLEND_MODE_HUE
  GSK_BLEND_MODE_SATURATION
  GSK_BLEND_MODE_LUMINOSITY
>;

constant GskCorner is export := guint32;
our enum GskCornerEnum is export <
  GSK_CORNER_TOP_LEFT
  GSK_CORNER_TOP_RIGHT
  GSK_CORNER_BOTTOM_RIGHT
  GSK_CORNER_BOTTOM_LEFT
>;

our constant GskFillRule is export := guint32;
our enum GskFillRuleEnum is export <
  GSK_FILL_RULE_WINDING
  GSK_FILL_RULE_EVEN_ODD
>;

constant GskGLUniformType is export := guint32;
our enum GskGLUniformTypeEnum is export <
  GSK_GL_UNIFORM_TYPE_NONE
  GSK_GL_UNIFORM_TYPE_FLOAT
  GSK_GL_UNIFORM_TYPE_INT
  GSK_GL_UNIFORM_TYPE_UINT
  GSK_GL_UNIFORM_TYPE_BOOL
  GSK_GL_UNIFORM_TYPE_VEC2
  GSK_GL_UNIFORM_TYPE_VEC3
  GSK_GL_UNIFORM_TYPE_VEC4
>;

our constant GskLineCap is export := guint32;
our enum GskLineCapEnum is export <
  GSK_LINE_CAP_BUTT
  GSK_LINE_CAP_ROUND
  GSK_LINE_CAP_SQUAR
>;

our constant GskLineJoin is export := guint32;
our enum GskLineJoinEnum is export <
  GSK_LINE_JOIN_MITER
  GSK_LINE_JOIN_ROUND
  GSK_LINE_JOIN_BEVEL
>;

constant GskPathDirection is export := guint32;
our enum GskPathDirectionEnum is export <
  GSK_PATH_FROM_START
  GSK_PATH_TO_START
  GSK_PATH_TO_END
  GSK_PATH_FROM_END
>;

our constant GskPathForeachFlags is export := guint32;
our enum GskPathForeachFlagsEnum is export (
  GSK_PATH_FOREACH_ALLOW_ONLY_LINES => 0,
  GSK_PATH_FOREACH_ALLOW_QUAD       => 1,
  GSK_PATH_FOREACH_ALLOW_CUBIC      => 1 +< 1,
  GSK_PATH_FOREACH_ALLOW_CONIC      => 1 +< 2
);

our constant GskPathOperation is export := guint32;
our enum GskPathOperationEnum is export <
  GSK_PATH_MOVE
  GSK_PATH_CLOSE
  GSK_PATH_LINE
  GSK_PATH_QUAD
  GSK_PATH_CUBIC
  GSK_PATH_CONIC
>;

constant GskRenderNodeType is export := guint32;
our enum GskRenderNodeTypeEnum is export <
  GSK_NOT_A_RENDER_NODE
  GSK_CONTAINER_NODE
  GSK_CAIRO_NODE
  GSK_COLOR_NODE
  GSK_LINEAR_GRADIENT_NODE
  GSK_REPEATING_LINEAR_GRADIENT_NODE
  GSK_RADIAL_GRADIENT_NODE
  GSK_REPEATING_RADIAL_GRADIENT_NODE
  GSK_CONIC_GRADIENT_NODE
  GSK_BORDER_NODE
  GSK_TEXTURE_NODE
  GSK_INSET_SHADOW_NODE
  GSK_OUTSET_SHADOW_NODE
  GSK_TRANSFORM_NODE
  GSK_OPACITY_NODE
  GSK_COLOR_MATRIX_NODE
  GSK_REPEAT_NODE
  GSK_CLIP_NODE
  GSK_ROUNDED_CLIP_NODE
  GSK_SHADOW_NODE
  GSK_BLEND_NODE
  GSK_CROSS_FADE_NODE
  GSK_TEXT_NODE
  GSK_BLUR_NODE
  GSK_DEBUG_NODE
  GSK_GL_SHADER_NODE
>;

constant GskScalingFilter is export := guint32;
our enum GskScalingFilterEnum is export <
  GSK_SCALING_FILTER_LINEAR
  GSK_SCALING_FILTER_NEAREST
  GSK_SCALING_FILTER_TRILINEAR
>;

constant GskSerializationError is export := guint32;
our enum GskSerializationErrorEnum is export <
  GSK_SERIALIZATION_UNSUPPORTED_FORMAT
  GSK_SERIALIZATION_UNSUPPORTED_VERSION
  GSK_SERIALIZATION_INVALID_DATA
>;

constant GskTransformCategory is export := guint32;
our enum GskTransformCategoryEnum is export <
  GSK_TRANSFORM_CATEGORY_UNKNOWN
  GSK_TRANSFORM_CATEGORY_ANY
  GSK_TRANSFORM_CATEGORY_3D
  GSK_TRANSFORM_CATEGORY_2D
  GSK_TRANSFORM_CATEGORY_2D_AFFINE
  GSK_TRANSFORM_CATEGORY_2D_TRANSLATE
  GSK_TRANSFORM_CATEGORY_IDENTITY
>;
